In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('AMZN.USUSD_Candlestick_1_M_BID_01.03.2020-10.07.2020.csv')
#dataset['Local time'] = datetime.strptime(dataset['Local time'], full)
dataset.index = dataset['Local time']
dataset = dataset.drop('Local time', axis =1 )
dataset

Open      High       Low     Close  Volume
Local time                                                              
02.03.2020 18:30:00.000   1903.667  1913.607  1902.578  1906.018  0.2750
02.03.2020 18:31:00.000   1905.868  1907.287  1899.998  1905.148  0.2355
02.03.2020 18:32:00.000   1905.148  1908.068  1896.007  1896.007  0.2635
02.03.2020 18:33:00.000   1896.008  1903.697  1895.007  1895.747  0.2395
02.03.2020 18:34:00.000   1895.467  1896.327  1890.737  1891.437  0.2912
...                            ...       ...       ...       ...     ...
10.07.2020 23:55:00.000   3198.538  3202.898  3198.117  3201.808  0.1975
10.07.2020 23:56:00.000   3201.807  3202.388  3200.768  3201.458  0.1415
10.07.2020 23:57:00.000   3200.778  3204.018  3200.777  3202.198  0.1390
10.07.2020 23:58:00.000   3201.598  3206.208  3201.597  3204.798  0.2650
10.07.2020 23:59:00.000   3204.838  3205.388  3201.598  3201.997  0.3158

[35808 rows x 5 columns]

In [ ]:
dataset['percentage change'] = 100*(dataset['Close']-dataset['Open'])/dataset['Open']
dataset

Open      High  ...  Volume  percentage change
Local time                                    ...                           
02.03.2020 18:30:00.000   1903.667  1913.607  ...  0.2750           0.123498
02.03.2020 18:31:00.000   1905.868  1907.287  ...  0.2355          -0.037778
02.03.2020 18:32:00.000   1905.148  1908.068  ...  0.2635          -0.479805
02.03.2020 18:33:00.000   1896.008  1903.697  ...  0.2395          -0.013766
02.03.2020 18:34:00.000   1895.467  1896.327  ...  0.2912          -0.212613
...                            ...       ...  ...     ...                ...
10.07.2020 23:55:00.000   3198.538  3202.898  ...  0.1975           0.102234
10.07.2020 23:56:00.000   3201.807  3202.388  ...  0.1415          -0.010900
10.07.2020 23:57:00.000   3200.778  3204.018  ...  0.1390           0.044364
10.07.2020 23:58:00.000   3201.598  3206.208  ...  0.2650           0.099950
10.07.2020 23:59:00.000   3204.838  3205.388  ...  0.3158          -0.088647

[35808 rows x 6 columns]

In [ ]:
dataset['percentage_pred'] = dataset['percentage change'].shift(-390)

In [ ]:
dataset.loc[dataset['percentage_pred']<0,'Invest'] = int(0)
dataset.loc[dataset['percentage_pred']>=0, 'Invest'] = int(1)
dataset

Open      High  ...  percentage_pred  Invest
Local time                                    ...                         
02.03.2020 18:30:00.000   1903.667  1913.607  ...        -0.511861     0.0
02.03.2020 18:31:00.000   1905.868  1907.287  ...        -0.000510     0.0
02.03.2020 18:32:00.000   1905.148  1908.068  ...        -0.161116     0.0
02.03.2020 18:33:00.000   1896.008  1903.697  ...         0.371150     1.0
02.03.2020 18:34:00.000   1895.467  1896.327  ...        -0.397803     0.0
...                            ...       ...  ...              ...     ...
10.07.2020 23:55:00.000   3198.538  3202.898  ...              NaN     NaN
10.07.2020 23:56:00.000   3201.807  3202.388  ...              NaN     NaN
10.07.2020 23:57:00.000   3200.778  3204.018  ...              NaN     NaN
10.07.2020 23:58:00.000   3201.598  3206.208  ...              NaN     NaN
10.07.2020 23:59:00.000   3204.838  3205.388  ...              NaN     NaN

[35808 rows x 8 columns]

In [ ]:
X = dataset[['percentage change','Volume','Close','Low','High','Open']].values
y = dataset[['Invest']].values
print(X)
print(y)

[[ 1.23498490e-01  2.75000000e-01  1.90601800e+03  1.90257800e+03
   1.91360700e+03  1.90366700e+03]
 [-3.77780623e-02  2.35500000e-01  1.90514800e+03  1.89999800e+03
   1.90728700e+03  1.90586800e+03]
 [-4.79805243e-01  2.63500000e-01  1.89600700e+03  1.89600700e+03
   1.90806800e+03  1.90514800e+03]
 ...
 [ 4.43642140e-02  1.39000000e-01  3.20219800e+03  3.20077700e+03
   3.20401800e+03  3.20077800e+03]
 [ 9.99500874e-02  2.65000000e-01  3.20479800e+03  3.20159700e+03
   3.20620800e+03  3.20159800e+03]
 [-8.86472265e-02  3.15800000e-01  3.20199700e+03  3.20159800e+03
   3.20538800e+03  3.20483800e+03]]
[[ 0.]
 [ 0.]
 [ 0.]
 ...
 [nan]
 [nan]
 [nan]]


In [ ]:
X = X[:-390]
print(X)
y = y[:-390]

[[ 1.23498490e-01  2.75000000e-01  1.90601800e+03  1.90257800e+03
   1.91360700e+03  1.90366700e+03]
 [-3.77780623e-02  2.35500000e-01  1.90514800e+03  1.89999800e+03
   1.90728700e+03  1.90586800e+03]
 [-4.79805243e-01  2.63500000e-01  1.89600700e+03  1.89600700e+03
   1.90806800e+03  1.90514800e+03]
 ...
 [ 7.70796650e-02  1.20000000e-01  3.18227800e+03  3.17886800e+03
   3.18227800e+03  3.17982700e+03]
 [-1.57120151e-02  1.81300000e-01  3.18177800e+03  3.18001700e+03
   3.18399800e+03  3.18227800e+03]
 [ 5.09213303e-02  3.92500000e-01  3.18299800e+03  3.18000700e+03
   3.18476700e+03  3.18137800e+03]]


In [ ]:
print(y)

[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [0.]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.15,random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 296 2322]
 [ 301 2394]]


0.5063052889139845

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

Accuracy: 50.68 %
Standard Deviation: 0.61 %


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':np.arange(0.1,1,0.1), 'kernel': ['linear']},
              {'C': np.arange(0.1,1,0.1), 'kernel': ['rbf'], 'gamma': [0.1,0.2,0.3,0.5,0.6,0.7,0.8,0.9], 'degree':[2,3,4,5,6,7,8]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(X_train, y_train) 
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print(" Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best parameters:", best_parameters)