In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
dataset = pd.read_csv('AMZN.USUSD_Candlestick_1_M_BID_01.03.2020-10.07.2020.csv')
dataset = dataset.drop('Local time', axis =1 )

In [3]:
dataset

Open      High       Low     Close  Volume
0      1903.667  1913.607  1902.578  1906.018  0.2750
1      1905.868  1907.287  1899.998  1905.148  0.2355
2      1905.148  1908.068  1896.007  1896.007  0.2635
3      1896.008  1903.697  1895.007  1895.747  0.2395
4      1895.467  1896.327  1890.737  1891.437  0.2912
...         ...       ...       ...       ...     ...
35803  3198.538  3202.898  3198.117  3201.808  0.1975
35804  3201.807  3202.388  3200.768  3201.458  0.1415
35805  3200.778  3204.018  3200.777  3202.198  0.1390
35806  3201.598  3206.208  3201.597  3204.798  0.2650
35807  3204.838  3205.388  3201.598  3201.997  0.3158

[35808 rows x 5 columns]

In [4]:
X = dataset[['Close', 'Open', 'High', 'Low', 'Volume']].values
y = dataset['Close'].shift(-390)

In [5]:
X = X[:-390]
print(X)
y = y[:-390]
print(y)

[[1.906018e+03 1.903667e+03 1.913607e+03 1.902578e+03 2.750000e-01]
 [1.905148e+03 1.905868e+03 1.907287e+03 1.899998e+03 2.355000e-01]
 [1.896007e+03 1.905148e+03 1.908068e+03 1.896007e+03 2.635000e-01]
 ...
 [3.182278e+03 3.179827e+03 3.182278e+03 3.178868e+03 1.200000e-01]
 [3.181778e+03 3.182278e+03 3.183998e+03 3.180017e+03 1.813000e-01]
 [3.182998e+03 3.181378e+03 3.184767e+03 3.180007e+03 3.925000e-01]]
0        1962.898
1        1961.917
2        1958.777
3        1966.047
4        1958.227
           ...   
35413    3201.808
35414    3201.458
35415    3202.198
35416    3204.798
35417    3201.997
Name: Close, Length: 35418, dtype: float64


In [6]:
X_train = X[:len(X)-390]
X_test = X[len(X)-390:]
y_train = y[:len(y)-390]
y_test = y[len(y)-390:]

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
X_train

array([[-1.21873871, -1.22577431, -1.20163778, -1.22338626,  1.82667275],
       [-1.22135279, -1.21916127, -1.22064294, -1.23113133,  1.23183118],
       [-1.24881858, -1.22132455, -1.21829436, -1.24311217,  1.65349103],
       ...,
       [ 2.30950567,  2.30861576,  2.30887712,  2.30049725,  0.26050762],
       [ 2.31374228,  2.3066658 ,  2.31432005,  2.30782205,  0.75294608],
       [ 2.31037703,  2.31459785,  2.31314426,  2.31010354,  2.9907551 ]])

In [9]:
X_test

array([[ 2.39315902,  2.41074393,  2.41112008,  2.39556948, -0.03314834],
       [ 2.39427075,  2.39304404,  2.39253591,  2.3888751 , -0.20934192],
       [ 2.4268415 ,  2.39518028,  2.42576487,  2.39770088, -0.43221927],
       ...,
       [ 2.61601625,  2.60853144,  2.61344084,  2.60799152, -0.50751567],
       [ 2.61451391,  2.61589563,  2.61861313,  2.61144078,  0.4156182 ],
       [ 2.61817962,  2.61319152,  2.62092563,  2.61141076,  3.59613816]])

In [10]:
y_train

0        1962.898
1        1961.917
2        1958.777
3        1966.047
4        1958.227
           ...   
35023    3179.338
35024    3179.558
35025    3182.278
35026    3181.778
35027    3182.998
Name: Close, Length: 35028, dtype: float64

In [11]:
y_test

35028    3188.998
35029    3210.928
35030    3205.198
35031    3195.297
35032    3180.998
           ...   
35413    3201.808
35414    3201.458
35415    3202.198
35416    3204.798
35417    3201.997
Name: Close, Length: 390, dtype: float64

In [12]:
from sklearn.linear_model import LinearRegression
lin_regressor=LinearRegression()
lin_regressor.fit(X_train,y_train) # Here we are training the linearregression object on the data that we have
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 2) # Here we are making an instance of the PolynomialFeatures class that helps as to make a matrix  with that form of X^0+X^1+X^2 for all the X data 
X_poly = poly_reg.fit_transform(X_train) # Here we are fitting the polynomial feature and transofrmin the result on the X dataset
lin_reg_2 = LinearRegression() # Here we make an instance of the LinearRegression class that helps us to claculate the linear coeficients of the equation b0*X^0+b1*X^1+b2*X^2 
lin_reg_2.fit(X_poly, y_train) # Here we are fitting the datasets that we have from the polynomilafeature class and the y dataset in other words making the linear regression for the data

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
 y_pred = lin_reg_2.predict(poly_reg.transform(X_test))

In [14]:
import sklearn.metrics as sm
print("R2 score =", round(sm.r2_score(y_test, y_pred)))

R2 score = -7.0


In [15]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),np.array(y_test).reshape(len(y_test),1)),1))

[[3143.03053806 3188.998     ]
 [3166.5259839  3210.928     ]
 [3147.13036204 3205.198     ]
 [3163.3515106  3195.297     ]
 [3155.51452972 3180.998     ]
 [3157.96613309 3176.097     ]
 [3137.31210699 3165.998     ]
 [3124.64511105 3166.338     ]
 [3134.84420653 3168.168     ]
 [3152.55041725 3177.998     ]
 [3155.46414321 3180.498     ]
 [3172.6936418  3183.288     ]
 [3159.54446812 3174.647     ]
 [3155.22798836 3179.998     ]
 [3142.51825682 3184.118     ]
 [3147.12941631 3178.728     ]
 [3155.72333358 3176.508     ]
 [3149.81298139 3169.997     ]
 [3144.0932224  3168.398     ]
 [3154.79016625 3173.398     ]
 [3152.28972723 3173.627     ]
 [3160.00491628 3174.158     ]
 [3154.12317078 3167.398     ]
 [3163.21346395 3171.678     ]
 [3165.69243209 3163.767     ]
 [3175.16262724 3169.868     ]
 [3173.54933337 3171.638     ]
 [3153.87549428 3174.167     ]
 [3169.01020637 3175.938     ]
 [3169.02287265 3175.078     ]
 [3166.72536491 3163.348     ]
 [3170.31620944 3160.348     ]
 [3170.8