In [14]:
import numpy as np
import pandas as pd

In [15]:
dataset = pd.read_csv('AMZN.USUSD_Candlestick_1_M_BID_01.03.2020-10.07.2020.csv')
#dataset['Local time'] = datetime.strptime(dataset['Local time'], full)
dataset.index = dataset['Local time']
dataset = dataset.drop('Local time', axis =1 )
dataset

Open      High       Low     Close  Volume
Local time                                                              
02.03.2020 18:30:00.000   1903.667  1913.607  1902.578  1906.018  0.2750
02.03.2020 18:31:00.000   1905.868  1907.287  1899.998  1905.148  0.2355
02.03.2020 18:32:00.000   1905.148  1908.068  1896.007  1896.007  0.2635
02.03.2020 18:33:00.000   1896.008  1903.697  1895.007  1895.747  0.2395
02.03.2020 18:34:00.000   1895.467  1896.327  1890.737  1891.437  0.2912
...                            ...       ...       ...       ...     ...
10.07.2020 23:55:00.000   3198.538  3202.898  3198.117  3201.808  0.1975
10.07.2020 23:56:00.000   3201.807  3202.388  3200.768  3201.458  0.1415
10.07.2020 23:57:00.000   3200.778  3204.018  3200.777  3202.198  0.1390
10.07.2020 23:58:00.000   3201.598  3206.208  3201.597  3204.798  0.2650
10.07.2020 23:59:00.000   3204.838  3205.388  3201.598  3201.997  0.3158

[35808 rows x 5 columns]

In [16]:
dataset['percentage change'] = 100*(dataset['Close']-dataset['Open'])/dataset['Open']
dataset

Open      High  ...  Volume  percentage change
Local time                                    ...                           
02.03.2020 18:30:00.000   1903.667  1913.607  ...  0.2750           0.123498
02.03.2020 18:31:00.000   1905.868  1907.287  ...  0.2355          -0.037778
02.03.2020 18:32:00.000   1905.148  1908.068  ...  0.2635          -0.479805
02.03.2020 18:33:00.000   1896.008  1903.697  ...  0.2395          -0.013766
02.03.2020 18:34:00.000   1895.467  1896.327  ...  0.2912          -0.212613
...                            ...       ...  ...     ...                ...
10.07.2020 23:55:00.000   3198.538  3202.898  ...  0.1975           0.102234
10.07.2020 23:56:00.000   3201.807  3202.388  ...  0.1415          -0.010900
10.07.2020 23:57:00.000   3200.778  3204.018  ...  0.1390           0.044364
10.07.2020 23:58:00.000   3201.598  3206.208  ...  0.2650           0.099950
10.07.2020 23:59:00.000   3204.838  3205.388  ...  0.3158          -0.088647

[35808 rows x 6 columns]

In [17]:
dataset['percentage_pred'] = dataset['percentage change'].shift(-390)

In [18]:
dataset.loc[dataset['percentage_pred']<0,'Invest'] = int(0)
dataset.loc[dataset['percentage_pred']>=0, 'Invest'] = int(1)
dataset

Open      High  ...  percentage_pred  Invest
Local time                                    ...                         
02.03.2020 18:30:00.000   1903.667  1913.607  ...        -0.511861     0.0
02.03.2020 18:31:00.000   1905.868  1907.287  ...        -0.000510     0.0
02.03.2020 18:32:00.000   1905.148  1908.068  ...        -0.161116     0.0
02.03.2020 18:33:00.000   1896.008  1903.697  ...         0.371150     1.0
02.03.2020 18:34:00.000   1895.467  1896.327  ...        -0.397803     0.0
...                            ...       ...  ...              ...     ...
10.07.2020 23:55:00.000   3198.538  3202.898  ...              NaN     NaN
10.07.2020 23:56:00.000   3201.807  3202.388  ...              NaN     NaN
10.07.2020 23:57:00.000   3200.778  3204.018  ...              NaN     NaN
10.07.2020 23:58:00.000   3201.598  3206.208  ...              NaN     NaN
10.07.2020 23:59:00.000   3204.838  3205.388  ...              NaN     NaN

[35808 rows x 8 columns]

In [19]:
X = dataset[['percentage change','Volume','Close','Low','High','Open']].values
y = dataset[['Invest']].values
print(X)
print(y)

[[ 1.23498490e-01  2.75000000e-01  1.90601800e+03  1.90257800e+03
   1.91360700e+03  1.90366700e+03]
 [-3.77780623e-02  2.35500000e-01  1.90514800e+03  1.89999800e+03
   1.90728700e+03  1.90586800e+03]
 [-4.79805243e-01  2.63500000e-01  1.89600700e+03  1.89600700e+03
   1.90806800e+03  1.90514800e+03]
 ...
 [ 4.43642140e-02  1.39000000e-01  3.20219800e+03  3.20077700e+03
   3.20401800e+03  3.20077800e+03]
 [ 9.99500874e-02  2.65000000e-01  3.20479800e+03  3.20159700e+03
   3.20620800e+03  3.20159800e+03]
 [-8.86472265e-02  3.15800000e-01  3.20199700e+03  3.20159800e+03
   3.20538800e+03  3.20483800e+03]]
[[ 0.]
 [ 0.]
 [ 0.]
 ...
 [nan]
 [nan]
 [nan]]


In [20]:
X = X[:-390]
print(X)
y = y[:-390]

[[ 1.23498490e-01  2.75000000e-01  1.90601800e+03  1.90257800e+03
   1.91360700e+03  1.90366700e+03]
 [-3.77780623e-02  2.35500000e-01  1.90514800e+03  1.89999800e+03
   1.90728700e+03  1.90586800e+03]
 [-4.79805243e-01  2.63500000e-01  1.89600700e+03  1.89600700e+03
   1.90806800e+03  1.90514800e+03]
 ...
 [ 7.70796650e-02  1.20000000e-01  3.18227800e+03  3.17886800e+03
   3.18227800e+03  3.17982700e+03]
 [-1.57120151e-02  1.81300000e-01  3.18177800e+03  3.18001700e+03
   3.18399800e+03  3.18227800e+03]
 [ 5.09213303e-02  3.92500000e-01  3.18299800e+03  3.18000700e+03
   3.18476700e+03  3.18137800e+03]]


In [21]:
print(y)

[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [0.]]


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.15,random_state = 0)

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [24]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors = 5, weights = 'distance', metric='minkowski',p=2, n_jobs = -1)
KNN.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='distance')

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = KNN.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1271 1347]
 [1285 1410]]


0.5046113306982872

In [26]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = KNN, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:515: DataConversionWarning: A column-vector y was passed when

Accuracy: 49.70 %
Standard Deviation: 1.05 %


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
