# Artificial Neural Network

### Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Modified.csv')
dataset

Local time      Open  ...     Close        Volume
0       20.07.2017 17:30:00.000 GMT+0400  1031.460  ...  1031.273  4.000000e-01
1       20.07.2017 17:31:00.000 GMT+0400  1031.580  ...  1031.210  3.300000e-01
2       20.07.2017 17:32:00.000 GMT+0400  1031.280  ...  1032.190  4.800000e-01
3       20.07.2017 17:33:00.000 GMT+0400  1032.380  ...  1033.770  4.100000e-01
4       20.07.2017 17:34:00.000 GMT+0400  1033.770  ...  1033.400  4.200000e-01
...                                  ...       ...  ...       ...           ...
292739  20.07.2020 23:55:00.000 GMT+0400  3198.178  ...  3198.318  1.816000e-07
292740  20.07.2020 23:56:00.000 GMT+0400  3198.778  ...  3196.488  2.520000e-07
292741  20.07.2020 23:57:00.000 GMT+0400  3196.818  ...  3196.058  2.172000e-07
292742  20.07.2020 23:58:00.000 GMT+0400  3196.058  ...  3198.998  3.612000e-07
292743  20.07.2020 23:59:00.000 GMT+0400  3198.997  ...  3194.108  4.596000e-07

[292744 rows x 6 columns]

In [ ]:
dataset['pred_close'] = dataset['Close'].shift(-390)

In [ ]:
X = dataset[['Open','High','Low','Close','Volume']].values
y = dataset[['pred_close']].values
print(X)
print(y)

[[1.031460e+03 1.031610e+03 1.030300e+03 1.031273e+03 4.000000e-01]
 [1.031580e+03 1.031580e+03 1.030500e+03 1.031210e+03 3.300000e-01]
 [1.031280e+03 1.033570e+03 1.031100e+03 1.032190e+03 4.800000e-01]
 ...
 [3.196818e+03 3.198488e+03 3.195528e+03 3.196058e+03 2.172000e-07]
 [3.196058e+03 3.200138e+03 3.195527e+03 3.198998e+03 3.612000e-07]
 [3.198997e+03 3.200768e+03 3.194108e+03 3.194108e+03 4.596000e-07]]
[[1013.27 ]
 [1014.805]
 [1017.01 ]
 ...
 [     nan]
 [     nan]
 [     nan]]


In [ ]:
dataset

Local time      Open  ...        Volume  pred_close
0       20.07.2017 17:30:00.000 GMT+0400  1031.460  ...  4.000000e-01    1013.270
1       20.07.2017 17:31:00.000 GMT+0400  1031.580  ...  3.300000e-01    1014.805
2       20.07.2017 17:32:00.000 GMT+0400  1031.280  ...  4.800000e-01    1017.010
3       20.07.2017 17:33:00.000 GMT+0400  1032.380  ...  4.100000e-01    1018.253
4       20.07.2017 17:34:00.000 GMT+0400  1033.770  ...  4.200000e-01    1018.711
...                                  ...       ...  ...           ...         ...
292739  20.07.2020 23:55:00.000 GMT+0400  3198.178  ...  1.816000e-07         NaN
292740  20.07.2020 23:56:00.000 GMT+0400  3198.778  ...  2.520000e-07         NaN
292741  20.07.2020 23:57:00.000 GMT+0400  3196.818  ...  2.172000e-07         NaN
292742  20.07.2020 23:58:00.000 GMT+0400  3196.058  ...  3.612000e-07         NaN
292743  20.07.2020 23:59:00.000 GMT+0400  3198.997  ...  4.596000e-07         NaN

[292744 rows x 7 columns]

In [ ]:
X = X[:-390]
print(X)
y = y[:-390]
print(y)

[[1.031460e+03 1.031610e+03 1.030300e+03 1.031273e+03 4.000000e-01]
 [1.031580e+03 1.031580e+03 1.030500e+03 1.031210e+03 3.300000e-01]
 [1.031280e+03 1.033570e+03 1.031100e+03 1.032190e+03 4.800000e-01]
 ...
 [2.957197e+03 2.957378e+03 2.954997e+03 2.957307e+03 2.475000e-01]
 [2.957307e+03 2.960088e+03 2.956697e+03 2.958237e+03 4.265000e-01]
 [2.959008e+03 2.961558e+03 2.958778e+03 2.960068e+03 4.800000e-01]]
[[1013.27 ]
 [1014.805]
 [1017.01 ]
 ...
 [3196.058]
 [3198.998]
 [3194.108]]


In [ ]:
X_train = X[:len(X)-390]
X_test = X[len(X)-390:]
y_train = y[:len(y)-390]
y_test = y[len(y)-390:]

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) # In deep learning it is important to feature scale all the variables even the binary ones or the dummy variables 
X_test = sc.transform(X_test) 

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
9124/9124 [==============================] - 14s 2ms/step - loss: 77977.8047
Epoch 2/100
9124/9124 [==============================] - 15s 2ms/step - loss: 1264.1804
Epoch 3/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1261.0692
Epoch 4/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1254.9082
Epoch 5/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1253.6416
Epoch 6/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1253.5204
Epoch 7/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1257.0596
Epoch 8/100
9124/9124 [==============================] - 15s 2ms/step - loss: 1252.2047
Epoch 9/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1250.7341
Epoch 10/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1253.1310
Epoch 11/100
9124/9124 [==============================] - 20s 2ms/step - loss: 1252.8829
Epoch 12/100
9124/9124 [=====

## Part 4 - Making the predictions and evaluating the model

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

array([[3031.28, 3010.3 ],
       [3036.55, 3012.79],
       [3038.03, 3015.54],
       [3038.44, 3014.  ],
       [3036.29, 3009.44],
       [3043.79, 3002.  ],
       [3045.25, 3000.76],
       [3039.89, 2999.02],
       [3039.36, 3002.01],
       [3038.5 , 3015.84],
       [3035.71, 3012.38],
       [3030.23, 3015.54],
       [3028.29, 3015.6 ],
       [3025.96, 3013.49],
       [3013.96, 3014.  ],
       [3011.62, 3022.78],
       [3011.87, 3029.26],
       [3013.89, 3036.19],
       [3009.58, 3036.71],
       [3006.89, 3029.33],
       [3017.66, 3033.81],
       [3021.61, 3044.28],
       [3020.92, 3040.98],
       [3022.33, 3051.44],
       [3020.84, 3058.47],
       [3021.69, 3058.85],
       [3022.1 , 3066.84],
       [3022.07, 3054.69],
       [3023.1 , 3047.6 ],
       [3026.47, 3043.73],
       [3030.22, 3044.23],
       [3029.22, 3042.33],
       [3020.24, 3041.2 ],
       [3018.69, 3050.4 ],
       [3010.14, 3050.86],
       [3017.85, 3052.74],
       [3023.59, 3056.  ],
 

In [ ]:
dataset['pred_open'] = dataset['Open'].shift(-390)
y2 = dataset[['pred_open']].values
print(X)
print(y2)

[[1.03e+03 1.03e+03 1.03e+03 1.03e+03 4.00e-01]
 [1.03e+03 1.03e+03 1.03e+03 1.03e+03 3.30e-01]
 [1.03e+03 1.03e+03 1.03e+03 1.03e+03 4.80e-01]
 ...
 [2.96e+03 2.96e+03 2.95e+03 2.96e+03 2.47e-01]
 [2.96e+03 2.96e+03 2.96e+03 2.96e+03 4.26e-01]
 [2.96e+03 2.96e+03 2.96e+03 2.96e+03 4.80e-01]]
[[1021.01]
 [1013.72]
 [1014.8 ]
 ...
 [    nan]
 [    nan]
 [    nan]]


In [ ]:
y2 = y2[:-390]
print(X)
print(y2)

[[1.03e+03 1.03e+03 1.03e+03 1.03e+03 4.00e-01]
 [1.03e+03 1.03e+03 1.03e+03 1.03e+03 3.30e-01]
 [1.03e+03 1.03e+03 1.03e+03 1.03e+03 4.80e-01]
 ...
 [2.96e+03 2.96e+03 2.95e+03 2.96e+03 2.47e-01]
 [2.96e+03 2.96e+03 2.96e+03 2.96e+03 4.26e-01]
 [2.96e+03 2.96e+03 2.96e+03 2.96e+03 4.80e-01]]
[[1021.01]
 [1013.72]
 [1014.8 ]
 ...
 [3196.82]
 [3196.06]
 [3199.  ]]


In [ ]:
y2_train = y2[:len(y2)-390]
y2_test = y2[len(y2)-390:]

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
ann.fit(X_train, y2_train, batch_size=32, epochs=100)

Epoch 1/100
9124/9124 [==============================] - 14s 2ms/step - loss: 65940.8906
Epoch 2/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1287.1517
Epoch 3/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1282.1617
Epoch 4/100
9124/9124 [==============================] - 15s 2ms/step - loss: 1279.6433
Epoch 5/100
9124/9124 [==============================] - 15s 2ms/step - loss: 1280.0088
Epoch 6/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1280.1938
Epoch 7/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1271.1892
Epoch 8/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1277.1289
Epoch 9/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1268.9310
Epoch 10/100
9124/9124 [==============================] - 14s 2ms/step - loss: 1267.9182
Epoch 11/100
9124/9124 [==============================] - 15s 2ms/step - loss: 1267.8395
Epoch 12/100
9124/9124 [=====

In [ ]:
y2_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
np.concatenate((y_pred.reshape(len(y2_pred),1),y_test.reshape(len(y2_test),1)),1)

array([[3031.28, 3010.3 ],
       [3036.55, 3012.79],
       [3038.03, 3015.54],
       [3038.44, 3014.  ],
       [3036.29, 3009.44],
       [3043.79, 3002.  ],
       [3045.25, 3000.76],
       [3039.89, 2999.02],
       [3039.36, 3002.01],
       [3038.5 , 3015.84],
       [3035.71, 3012.38],
       [3030.23, 3015.54],
       [3028.29, 3015.6 ],
       [3025.96, 3013.49],
       [3013.96, 3014.  ],
       [3011.62, 3022.78],
       [3011.87, 3029.26],
       [3013.89, 3036.19],
       [3009.58, 3036.71],
       [3006.89, 3029.33],
       [3017.66, 3033.81],
       [3021.61, 3044.28],
       [3020.92, 3040.98],
       [3022.33, 3051.44],
       [3020.84, 3058.47],
       [3021.69, 3058.85],
       [3022.1 , 3066.84],
       [3022.07, 3054.69],
       [3023.1 , 3047.6 ],
       [3026.47, 3043.73],
       [3030.22, 3044.23],
       [3029.22, 3042.33],
       [3020.24, 3041.2 ],
       [3018.69, 3050.4 ],
       [3010.14, 3050.86],
       [3017.85, 3052.74],
       [3023.59, 3056.  ],
 

In [ ]:
y_pred_change = np.subtract(y_pred,y2_pred)
y_real_change = np.subtract(y_test,y2_test)

In [ ]:
np.concatenate((y_pred_change.reshape(len(y_pred_change),1),y_real_change.reshape(len(y_real_change),1)),1)

array([[ 1.05e+01,  1.22e+01],
       [ 9.90e+00,  2.49e+00],
       [ 1.73e+01,  2.39e+00],
       [ 2.36e+01, -2.00e+00],
       [ 3.72e+01, -5.06e+00],
       [ 3.81e+01, -4.71e+00],
       [ 2.60e+01, -1.24e+00],
       [ 2.80e+01, -1.74e+00],
       [ 2.49e+01,  3.38e+00],
       [ 2.73e+01,  1.24e+01],
       [ 2.80e+01, -3.96e+00],
       [ 3.03e+01,  2.69e+00],
       [ 1.77e+01,  6.00e-02],
       [ 1.72e+01, -1.51e+00],
       [ 1.15e+01,  5.10e-01],
       [ 1.75e+01,  8.77e+00],
       [ 1.07e+01,  6.48e+00],
       [ 1.80e+01,  6.93e+00],
       [ 1.88e+01,  5.20e-01],
       [ 1.05e+01, -7.38e+00],
       [ 2.22e+01,  4.54e+00],
       [ 2.14e+01,  1.02e+01],
       [ 2.11e+01, -3.30e+00],
       [ 2.45e+01,  1.04e+01],
       [ 1.53e+01,  7.03e+00],
       [ 2.15e+01,  3.71e-01],
       [ 2.60e+01,  7.75e+00],
       [ 2.33e+01, -1.09e+01],
       [ 1.66e+01, -7.09e+00],
       [ 1.72e+01, -4.27e+00],
       [ 2.58e+01, -1.84e+00],
       [ 2.71e+01, -1.90e+00],
       [

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(np.sign(y_pred_change),np.sign(y_real_change)) 

0.5435897435897435

In [7]:
crypto = {'ETH':10, 'ZEC':37, 'BTC':98, 'BCH':25, 'XRP':20}
values = crypto.values()
#Return values of a dictionary    
total = sum(values)
print(float(total))

190.0


In [31]:
balance = 1e5

crypto = {'ETH':10, 'ZEC':37, 'BTC':98, 'BCH':25, 'XRP':20}

invested = crypto.copy()
i = 0
for key in invested.keys():
  invested[key] = (balance*(invested[key]/total))

In [34]:
invested

{'BCH': 13157.894736842105,
 'BTC': 51578.94736842106,
 'ETH': 5263.157894736842,
 'XRP': 10526.315789473683,
 'ZEC': 19473.684210526317}

In [35]:
def intext(data, crypto):
  new_dict = data.copy()
  profit = data.copy()
  for key in data.keys():
    new_dict[key] = float(new_dict[key]) * (1 + (crypto[key]/100.0))
    new_dict[key] = 0.95*new_dict[key]
    profit[key] = new_dict[key] - data[key]
  
  return new_dict, profit, sum(profit.values())

In [37]:
after, profit, total_profit = intext(invested, crypto)

In [38]:
after

{'BCH': 15624.999999999998,
 'BTC': 97020.0,
 'ETH': 5500.0,
 'XRP': 11999.999999999998,
 'ZEC': 25345.000000000004}

In [39]:
profit

{'BCH': 2467.105263157893,
 'BTC': 45441.05263157894,
 'ETH': 236.84210526315837,
 'XRP': 1473.684210526315,
 'ZEC': 5871.315789473687}

In [40]:
total_profit

55489.99999999999