# SDS Challenge #4 - Hostel Listings

## Problem Statement

Welcome Data Scientist to the 4th SDS Club Monthly Challenge! In this month's challenge you have been hired by a hostel company to 
help them determine a fair price for their new hostels based on previous hostel data. Your mission to predict the price of each hostel based on the data provided.

## Evaluation

$$\begin{equation*}
MSE = {\frac{1}{n}\sum_{i=1}^{n}(y_{i} - \hat{y}_{i})^{2}}
\end{equation*}$$

## Understanding the Dataset

In the dataset there are 65 unique columns. Each column is properly and descriptively named in the dataset.

## Dataset Files

**public_listings.csv** - Dataset to train and analyze <br />
**pred_listings.csv** - Dataset to predict listings' prices

## Submission

All submissions should be sent through email to challenges@superdatascience.com. When submitting, the file should contain predictions made on the pred_listings.csv file, and it should have the following format:

In [ ]:
150.00
95.00
80.00
105.00
72.00

## Acknowledgements

The data was scraped and collected by Inside Airbnb from publicly available information on the Airbnb site.

## Importing the Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset and cleaning them

In [ ]:
dataset = pd.read_csv("public_cars.csv")
dataset_test = pd.read_csv("pred_cars.csv")

In [ ]:
dataset

manufacturer_name model_name  ... duration_listed price_usd
0                  Ford     Fusion  ...               7    4250.0
1                 Dodge    Caravan  ...             133    4000.0
2                  Ford     Galaxy  ...               0   10900.0
3                 Mazda          6  ...              20    6999.0
4                  Audi         80  ...             160    1600.0
...                 ...        ...  ...             ...       ...
30819             Mazda   Millenia  ...              66    2000.0
30820              Audi         A3  ...              58    8800.0
30821             Mazda        626  ...              87    1400.0
30822              Audi         A6  ...              52    3500.0
30823             Honda    Odyssey  ...              75   42000.0

[30824 rows x 26 columns]

In [ ]:
dataset_test

manufacturer_name model_name  ... feature_9 duration_listed
0              Renault     Megane  ...      True             114
1              Peugeot        206  ...      True              67
2           Volkswagen     Sharan  ...     False              50
3                Volvo       XC60  ...      True              79
4                Mazda          3  ...     False              74
...                ...        ...  ...       ...             ...
7702          Chrysler    Sebring  ...     False              81
7703             Geely  Emgrand 7  ...      True              84
7704          Chrysler    Sebring  ...     False               1
7705              Ford   EcoSport  ...      True               2
7706             Skoda      Fabia  ...     False              26

[7707 rows x 25 columns]

## Taking care of missing data

In [ ]:
dataset.drop(['manufacturer_name', 'model_name', 'color', 'body_type'],
  axis='columns', inplace=True)
dataset_test.drop(['manufacturer_name', 'model_name', 'color', 'body_type'],
  axis='columns', inplace=True)

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
dataset

transmission  odometer_value  ...  duration_listed price_usd
0       mechanical          245000  ...                7    4250.0
1        automatic          265542  ...              133    4000.0
2       mechanical          168000  ...                0   10900.0
3       mechanical          225522  ...               20    6999.0
4       mechanical          370000  ...              160    1600.0
...            ...             ...  ...              ...       ...
30819    automatic          360493  ...               66    2000.0
30820    automatic          117000  ...               58    8800.0
30821   mechanical          333000  ...               87    1400.0
30822    automatic          530000  ...               52    3500.0
30823    automatic           15000  ...               75   42000.0

[30824 rows x 22 columns]

In [ ]:
dataset_test

transmission  odometer_value  ...  feature_9 duration_listed
0      mechanical          360000  ...       True             114
1      mechanical          267000  ...       True              67
2      mechanical          172000  ...      False              50
3      mechanical          230000  ...       True              79
4      mechanical          206000  ...      False              74
...           ...             ...  ...        ...             ...
7702    automatic          347618  ...      False              81
7703    automatic            9700  ...       True              84
7704    automatic          111111  ...      False               1
7705   mechanical          109000  ...       True               2
7706   mechanical          180000  ...      False              26

[7707 rows x 21 columns]

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
X_test = dataset_test.values
imputer.fit(X[:, 6:7])
X[:, 6:7] = imputer.transform(X[:, 6:7])
X_test[:, 6:7] = imputer.transform(X_test[:, 6:7])

In [ ]:
print(X)
X.shape

[['mechanical' 245000 2006 ... False False 7]
 ['automatic' 265542 2002 ... False False 133]
 ['mechanical' 168000 2009 ... True True 0]
 ...
 ['mechanical' 333000 1997 ... False True 87]
 ['automatic' 530000 1995 ... True True 52]
 ['automatic' 15000 2018 ... True True 75]]


(30824, 21)

In [ ]:
print(X_test)
X_test.shape

[['mechanical' 360000 1997 ... False True 114]
 ['mechanical' 267000 1999 ... False True 67]
 ['mechanical' 172000 2000 ... False False 50]
 ...
 ['automatic' 111111 2001 ... False False 1]
 ['mechanical' 109000 2016 ... True True 2]
 ['mechanical' 180000 2000 ... False False 26]]


(7707, 21)

## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,18, 19])], remainder = 'passthrough' )
X = np.array(ct.fit_transform(X))
X_test = np.array(ct.transform(X_test))

In [ ]:
print(X_test)
X_test.shape

[[0.0 1.0 0.0 ... 1997 1.6 114]
 [0.0 1.0 0.0 ... 1999 1.4 67]
 [0.0 1.0 0.0 ... 2000 2.0 50]
 ...
 [1.0 0.0 0.0 ... 2001 2.4 1]
 [0.0 1.0 1.0 ... 2016 1.5 2]
 [0.0 1.0 0.0 ... 2000 1.4 26]]


(7707, 45)

In [ ]:
print(X)
X.shape

[[0.0 1.0 0.0 ... 2006 1.6 7]
 [1.0 0.0 0.0 ... 2002 3.3 133]
 [0.0 1.0 1.0 ... 2009 1.8 0]
 ...
 [0.0 1.0 0.0 ... 1997 2.0 87]
 [1.0 0.0 0.0 ... 1995 2.6 52]
 [1.0 0.0 0.0 ... 2018 3.5 75]]


(30824, 45)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)
X_test = sc.fit_transform(X_test)

In [ ]:
print(X)

[[-0.71001645  0.71001645 -0.70856972 ...  0.38022628 -0.6805601
  -0.65105271]
 [ 1.40841807 -1.40841807 -0.70856972 ... -0.11675116  1.86649355
   0.46740533]
 [-0.71001645  0.71001645  1.41129372 ...  0.75295936 -0.38090673
  -0.71318927]
 ...
 [-0.71001645  0.71001645 -0.70856972 ... -0.73797296 -0.08125336
   0.05907938]
 [ 1.40841807 -1.40841807 -0.70856972 ... -0.98646168  0.81770675
  -0.25160341]
 [ 1.40841807 -1.40841807 -0.70856972 ...  1.87115859  2.16614693
  -0.04744044]]


In [ ]:
from sklearn.cross_decomposition import PLSRegression
pls = PLSRegression(n_components=30)
X = pls.fit_transform(X, y)
X_test = pls.transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/cross_decomposition/_pls.py:351: UserWarning: X scores are null at iteration 25
  warnings.warn('X scores are null at iteration %s' % k)


In [ ]:
X = X[0]
print(X)

[[-3.2406207   1.30461024  0.60500718 ...  0.          0.
   0.        ]
 [-1.18948098 -0.12083718  0.40252081 ...  0.          0.
   0.        ]
 [ 2.25046596  1.0697606   0.82689294 ...  0.          0.
   0.        ]
 ...
 [-2.65499076 -1.04375939 -0.45875171 ...  0.          0.
   0.        ]
 [ 0.96429328 -1.62127777 -0.72155814 ...  0.          0.
   0.        ]
 [ 6.53432936 -0.24156533 -0.13357443 ...  0.          0.
   0.        ]]


## Making the ANN and training it on the Training set

In [ ]:
import tensorflow as tf
import time

In [ ]:
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [ ]:
!nvidia-smi

Sat Jan  2 00:17:10 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P0    27W /  70W |    227MiB / 15079MiB |      5%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
y = y.reshape(len(y), 1)
y.shape

(30824, 1)

In [ ]:
X.shape

(30824, 30)

### Initializing the ANN

In [ ]:
def build_model():
    with tf.device('/gpu:0'):
      ann = tf.keras.models.Sequential()

      ann.add(tf.keras.layers.Dense(units = 30, activation = 'relu'))

      ann.add(tf.keras.layers.Dense(units = 100, activation = 'relu'))

      ann.add(tf.keras.layers.Dense(units = 100, activation = 'relu'))

      ann.add(tf.keras.layers.Dense(units = 100, activation = 'relu'))

      ann.add(tf.keras.layers.Dense(units = 1, activation = 'relu'))

      start = time.time()
      ann.compile(loss="mean_squared_error", optimizer="adam")
      print("> Compilation Time : ", time.time() - start)
      return ann

In [ ]:
ann = build_model()

> Compilation Time :  0.015689373016357422


### Training the ANN model on the Training set

In [ ]:
ann.fit( x=X, y=y, batch_size=32, epochs = 100)

Epoch 1/100
964/964 [==============================] - 3s 2ms/step - loss: 34820210.3627
Epoch 2/100
964/964 [==============================] - 2s 2ms/step - loss: 8238422.2710
Epoch 3/100
964/964 [==============================] - 2s 2ms/step - loss: 7340960.5223
Epoch 4/100
964/964 [==============================] - 2s 2ms/step - loss: 7057146.0093
Epoch 5/100
964/964 [==============================] - 2s 2ms/step - loss: 6546161.4073
Epoch 6/100
964/964 [==============================] - 2s 2ms/step - loss: 6482783.7244
Epoch 7/100
964/964 [==============================] - 2s 2ms/step - loss: 6064273.8098
Epoch 8/100
964/964 [==============================] - 2s 2ms/step - loss: 5986963.5759
Epoch 9/100
964/964 [==============================] - 2s 2ms/step - loss: 5918654.1756
Epoch 10/100
964/964 [==============================] - 2s 2ms/step - loss: 5352434.0974
Epoch 11/100
964/964 [==============================] - 2s 2ms/step - loss: 5596686.1860
Epoch 12/100
964/964 [=======

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
print(y_pred)

[[ 2109.5005]
 [ 1813.2583]
 [ 2960.6238]
 ...
 [ 2654.2727]
 [14215.504 ]
 [ 1745.5387]]


## Building the csv file

In [ ]:
df = pd.DataFrame(y_pred, columns=["price_usd"])

df_total = pd.concat([pd.read_csv("pred_cars.csv"), df], axis=1)

print(df_total)

     manufacturer_name model_name  ... duration_listed     price_usd
0              Renault     Megane  ...             114   2109.500488
1              Peugeot        206  ...              67   1813.258301
2           Volkswagen     Sharan  ...              50   2960.623779
3                Volvo       XC60  ...              79  13271.837891
4                Mazda          3  ...              74   5188.108887
...                ...        ...  ...             ...           ...
7702          Chrysler    Sebring  ...              81   2515.612549
7703             Geely  Emgrand 7  ...              84  21078.427734
7704          Chrysler    Sebring  ...               1   2654.272705
7705              Ford   EcoSport  ...               2  14215.503906
7706             Skoda      Fabia  ...              26   1745.538696

[7707 rows x 26 columns]


In [ ]:
df_total.to_csv("pred_cars.csv", index=None)