# Support Vector Regression (SVR)

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

## Importing the dataset

In [2]:
dataset = pd.read_csv("Data.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Spliting the data into training and test sets

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [4]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [5]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


## Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)

sc_y = StandardScaler()
y_train = y_train.reshape(len(y_train), 1)
y_train = sc_y.fit_transform(y_train)

In [7]:
print(X_train)
X_train.shape

[[-1.13572795 -0.88685592  0.67357894  0.52070558]
 [-0.80630243 -0.00971567  0.45145467  0.14531044]
 [ 1.77128416  1.84743445  0.24279248 -1.88374143]
 ...
 [-0.38409993 -1.24886277  0.84522042  0.13092486]
 [-0.9232821  -1.04155299  1.54693117  0.8830852 ]
 [ 1.70136528  1.05824381 -1.20438076 -2.42285818]]


(7654, 4)

In [8]:
print(y_train)
y_train.shape

[[ 1.15069786]
 [ 0.79540777]
 [-1.30936356]
 ...
 [ 0.27595724]
 [ 0.49346982]
 [-1.53508417]]


(7654, 1)

## Training the SVR model on the whole dataset

In [9]:
from sklearn.svm import SVR

regressor = SVR(kernel = 'rbf')

regressor.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

## Predicting the test result

In [10]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_x.transform(X_test)))
y_pred = y_pred.reshape(len(y_pred), 1)
y_test = y_test.reshape(len(y_test), 1)
print(np.concatenate((y_pred, y_test), 1))

[[434.05242921 431.23      ]
 [457.93810186 460.01      ]
 [461.03113894 461.14      ]
 ...
 [470.60268461 473.26      ]
 [439.41653548 438.        ]
 [460.91757115 463.28      ]]


## Evaluate the model

In [11]:
from sklearn.metrics import r2_score

print("r2 =",r2_score(y_test, y_pred))
adjusted_r_squared = 1 - (1-r2_score(y_test, y_pred))*(len(y)-1)/(len(y)-X.shape[1]-1)
print("Adjusted r2 =", adjusted_r_squared)

r2 = 0.9480784049986258
Adjusted r2 = 0.9480566872970672
